package com.java.java_zaliczenie;
// Generated 2013-05-29 20:35:51 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer idCategory;
     private Set books = new HashSet(0);
     private Set adventures = new HashSet(0);
     private Set sfs = new HashSet(0);
     private Set dramas = new HashSet(0);

    public Category() {
    }

    public Category(Set books, Set adventures, Set sfs, Set dramas) {
       this.books = books;
       this.adventures = adventures;
       this.sfs = sfs;
       this.dramas = dramas;
    }
   
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }
    public Set getAdventures() {
        return this.adventures;
    }
    
    public void setAdventures(Set adventures) {
        this.adventures = adventures;
    }
    public Set getSfs() {
        return this.sfs;
    }
    
    public void setSfs(Set sfs) {
        this.sfs = sfs;
    }
    public Set getDramas() {
        return this.dramas;
    }
    
    public void setDramas(Set dramas) {
        this.dramas = dramas;
    }




}


