package com.java.java_zaliczenie;
// Generated 2013-05-29 20:35:51 by Hibernate Tools 3.2.1.GA



/**
 * Drama generated by hbm2java
 */
public class Drama  implements java.io.Serializable {


     private int categoryIdCategory;
     private Category category;

    public Drama() {
    }

    public Drama(int categoryIdCategory, Category category) {
       this.categoryIdCategory = categoryIdCategory;
       this.category = category;
    }
   
    public int getCategoryIdCategory() {
        return this.categoryIdCategory;
    }
    
    public void setCategoryIdCategory(int categoryIdCategory) {
        this.categoryIdCategory = categoryIdCategory;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }




}


