package com.java.java_zaliczenie;
// Generated 2013-05-29 19:46:30 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Shelf generated by hbm2java
 */
public class Shelf  implements java.io.Serializable {


     private Integer idShelf;
     private Stand stand;
     private Set books = new HashSet(0);

    public Shelf() {
    }

	
    public Shelf(Stand stand) {
        this.stand = stand;
    }
    public Shelf(Stand stand, Set books) {
       this.stand = stand;
       this.books = books;
    }
   
    public Integer getIdShelf() {
        return this.idShelf;
    }
    
    public void setIdShelf(Integer idShelf) {
        this.idShelf = idShelf;
    }
    public Stand getStand() {
        return this.stand;
    }
    
    public void setStand(Stand stand) {
        this.stand = stand;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


