package com.java.java_zaliczenie;
// Generated 2013-05-29 23:28:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Stand generated by hbm2java
 */
public class Stand  implements java.io.Serializable {


     private Integer idStand;
     private String standName;
     private Set shelfs = new HashSet(0);

    public Stand() {
    }

	
    public Stand(String standName) {
        this.standName = standName;
    }
    public Stand(String standName, Set shelfs) {
       this.standName = standName;
       this.shelfs = shelfs;
    }
   
    public Integer getIdStand() {
        return this.idStand;
    }
    
    public void setIdStand(Integer idStand) {
        this.idStand = idStand;
    }
    public String getStandName() {
        return this.standName;
    }
    
    public void setStandName(String standName) {
        this.standName = standName;
    }
    public Set getShelfs() {
        return this.shelfs;
    }
    
    public void setShelfs(Set shelfs) {
        this.shelfs = shelfs;
    }




}


